### ISSUE TITLE
Cannot find modules after update to 0.7.1

### ISSUE THREAD

**Issue by MuhKuh7** [swimlane/angular2-data-table#158]
After I updated with npm to version 0.7.1 I get the following 2 errors:

> node_modules/angular2-data-table/release/models/sort.model.d.ts(1,31): error TS2307: Cannot find module 'types/sort-direction.type'.
node_modules/angular2-data-table/release/models/table-options.model.d.ts(4,53): error TS2307: Cannot find module 'types'.

Going back to 0.6.1 fixes the issue.

**Comment by amcdnl** [comment]
Fixed in 0.7.2
