### ISSUE TITLE
Cannot read property '$$expanded' of null

### ISSUE THREAD

**Issue by ipassynk** [swimlane/angular2-data-table#225]
**I'm submitting a ...**  (check one with "x")

```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

After update 0.10.1 from to 0.11.2 the following exception is thrown:

```
error_handler.js:51 TypeError: Cannot read property '$$expanded' of null
    at RowHeightCache.initCache (index.js:3283)
    at StateService.refreshRowHeightCache (index.js:2567)
    at StateService.setRows (index.js:2575)
    at DataTable.ngDoCheck (index.js:850)
    at DebugAppView._View_SkuListGridComponent0.detectChangesInternal (SkuListGridComponent.ngfactory.js:329)
    at DebugAppView.AppView.detectChanges (view.js:272)
    at DebugAppView.detectChanges (view.js:377)
    at DebugAppView.AppView.detectViewChildrenChanges (view.js:298)
    at DebugAppView._View_SkuListComponent0.detectChangesInternal (SkuListComponent.ngfactory.js:101)
    at DebugAppView.AppView.detectChanges (view.js:272)ErrorHandler.handleError @ error_handler.js:51
error_handler.js:54 ERROR CONTEXT:
```

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Table version:** 0.7.x
  
  
- **Angular version:** 2.0.x
  
  
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Can you make a demo?

**Comment by ipassynk** [comment]
Here it is: https://plnkr.co/edit/u3zYSxq9z48TUATxvarE
The cause is empty row. We are working with big set of data and loading data dynamically BUT we need to have proportional v-scroll bar based on total number of records.

**Comment by amcdnl** [comment]
Fixed in latest
