### ISSUE TITLE
RxJS Support

### ISSUE THREAD

**Issue by amcdnl** [swimlane/angular2-data-table#32]
## Requirement

Add ability to pass RxJS results object and it operate async'ly.
## Examples
- Started inital here a while back: https://github.com/swimlane/angular2-data-table/commit/c897de809676470000dbeb4c2c6fe3460d00af8c#diff-900094e743286cbc60f440b5753cbb6a

**Comment by adrm** [comment]
What is the intent behind this? I think we can take advantage of the `async` pipe to meet this objective when using this component. Are you thinking in another kind of integration with RxJS?

**Comment by amcdnl** [comment]
Yes, that was my thought. The idea is to create a better interface for inserting data especially in a streaming manner from the server.

**Comment by stephenrichter** [comment]
I am trying to integrate a data-table with an RxJS Observable as opposed to an Array. Is there a workaround currently available using the async pipe or another option? I figure my issue is the data-table has no rows upon init, and throws a TypeError "rows.slice is not a function". 

Here's an example of what I'm trying to do:

`<datatable [rows]="todos$" [options]="options"></datatable>`

and in my todo-list.component.ts...

`todos$: Observable<Todo[]>;`

 `ngOnInit() { this.todos$ = this.todoService.todos$;
    this.todoService.getTodos(); // get all todos  }`

**Comment by shattar** [comment]
When I feed the rows with an array of objects, where the array of objects streams from an observable, the entire `<datatable>` loses state.  The selected row is lost, the sorting is reset, etc.

It seems like the `trackBy` index for `ngFor` is used internally by the data table component, so there is no way for the application to define equality to span the gap between individual rows between the old and new arrays of rows.  Much like the [Heroes Excercise](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ngFor) that explains how to use the `trackBy` feature.

Question, how should I use `<datatable>` with a stream from the server without the table losing its mind when it gets a whole new array of rows (even if the new array of rows has identical contents).

Is there a similar `trackBy` feature for `<datatable>` that keeps track of row equality across two row arrays?

**Comment by amcdnl** [comment]
@shattar - I'm actually working on a 1.0 version right now that uses all pushstate, that should enable us to more easily integrate rx. It will be released today.

RX is top of my list but sadly my rx experience is a bit sparse.  Any help on direction would be appreciated.

**Comment by shattar** [comment]
I think that the major thing necessary in order to 'support Rx' is to allow the array of rows to change without losing the selection and sorting.  No new dependencies or `Rx` constructs or anything like that.  

An example that points out the problem with the current strategy is [the Filter demo](http://swimlane.github.io/angular2-data-table/).  If you sort by a column, then filter, the sorting is wrecked (even though the component still thinks it's sorted).  This is indicated by #99.

I think that in order to solve this, there needs to be a mechanism for the application to define equivalence (trackBy) between elements of different `rows` arrays other than object identity.  This also means that the datatable component cannot continue to piggy-back on the applications objects to store its own state information inside (like `$$index`).  Instead, an internal _rows array could be created to store the component state information along with a reference to the applications row object, mirroring the applications rows array.  When the application provides a new rows array, the component could update its internal _rows array by using the applications provided `trackBy` function to determine element equivalency.  This would allow the application to provide a rows array that will not be molested by the datatable component, and the datatable component can still retain state.  The default `trackBy` function could be object equivalency.

As an aside, due to the fact that the applications rows array is hijacked by the component, the following code fails with an `ExpressionChangedAfterItHasBeenCheckedError` error.
```
<datatable 
  class="material"
  [rows]="rows"
  [columns]="columns"
  [columnMode]="'force'"
  [headerHeight]="50"
  [footerHeight]="50"
  [rowHeight]="'auto'">
 </datatable>
 <div *ngIf="jobs">
   <template ngFor let-row [ngForOf]="rows">
     <pre>{{row | json}}</pre>
    </template>
</div>
```

**Comment by amcdnl** [comment]
a first stab at this was done in 1.7.0
